# -*- coding: utf-8 -*-
"""Negative-Regularization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SlLSy9Srru_JKJzipuJ-ZmWjY1ePflE9

# Exp 1-4
"""

import numpy as np
import pandas as pd
from IPython.display import display

# ============================================================
# Negative Regularization: Synthetic Experiments 1--4
# Single-cell Colab code
# Output: exactly 4 tables (one per experiment)
# ============================================================

# -------------------------
# Global configuration
# -------------------------
SEED = 7
M = 12
N_TRAIN = 48
N_TEST = 600

# Population covariance eigenvalues (restricted representation)
EIGS = np.array([4.0, 3.0, 2.2, 1.5, 1.0, 0.7, 0.45, 0.28, 0.18, 0.11, 0.07, 0.04], dtype=float)
SQRT_SIG = np.diag(np.sqrt(EIGS))

# Weak-spectrum threshold kappa: weakest four directions
KAPPA = 0.20
WEAK_MASK = EIGS <= KAPPA

# -------------------------
# Helper functions
# -------------------------
def make_beta(mode: str) -> np.ndarray:
    if mode == "weak":
        # Most oracle mass on weak eigendirections
        return np.array([0.08, 0.08, 0.06, 0.05, 0.05, 0.04, 0.10, 0.16, 0.28, 0.36, 0.44, 0.52], dtype=float)
    if mode == "balanced":
        return np.array([0.18, 0.16, 0.15, 0.13, 0.12, 0.11, 0.10, 0.10, 0.10, 0.10, 0.10, 0.10], dtype=float)
    if mode == "strong":
        # Most oracle mass on strong eigendirections
        return np.array([0.52, 0.44, 0.36, 0.28, 0.18, 0.12, 0.08, 0.06, 0.05, 0.04, 0.03, 0.02], dtype=float)
    raise ValueError("mode must be one of {'weak', 'balanced', 'strong'}")

def sample_design(n: int, rng: np.random.Generator) -> np.ndarray:
    return rng.normal(size=(n, M)) @ SQRT_SIG

def sample_dataset(beta_true: np.ndarray, noise_std: float, n_train: int = N_TRAIN, n_test: int = N_TEST, seed: int = 0):
    rng = np.random.default_rng(seed)
    X_train = sample_design(n_train, rng)
    X_test  = sample_design(n_test, rng)
    y_train = X_train @ beta_true + rng.normal(scale=noise_std, size=n_train)
    y_test  = X_test  @ beta_true + rng.normal(scale=noise_std, size=n_test)
    return X_train, y_train, X_test, y_test

def sigma_hat(X: np.ndarray) -> np.ndarray:
    return (X.T @ X) / X.shape[0]

def g_hat(X: np.ndarray, y: np.ndarray) -> np.ndarray:
    return (X.T @ y) / X.shape[0]

def empirical_min_eig(X: np.ndarray) -> float:
    return float(np.linalg.eigvalsh(sigma_hat(X)).min())

def fit_direct_lambda(X: np.ndarray, y: np.ndarray, lam: float) -> np.ndarray:
    A = sigma_hat(X) + lam * np.eye(X.shape[1])
    return np.linalg.solve(A, g_hat(X, y))

def fit_baseline_adjusted(X: np.ndarray, y: np.ndarray, tau0: float, lam_adj: float) -> np.ndarray:
    eta = tau0 + lam_adj
    A = sigma_hat(X) + eta * np.eye(X.shape[1])
    return np.linalg.solve(A, g_hat(X, y))

def predict(X: np.ndarray, beta: np.ndarray) -> np.ndarray:
    return X @ beta

def mse(y_true: np.ndarray, y_pred: np.ndarray) -> float:
    return float(np.mean((y_true - y_pred) ** 2))

def empirical_df_direct(X: np.ndarray, lam: float) -> float:
    vals = np.linalg.eigvalsh(sigma_hat(X))
    if np.any(vals + lam <= 0):
        return np.nan
    return float(np.sum(vals / (vals + lam)))

def empirical_df_adjusted(X: np.ndarray, tau0: float, lam_adj: float) -> float:
    eta = tau0 + lam_adj
    vals = np.linalg.eigvalsh(sigma_hat(X))
    if np.any(vals + eta <= 0):
        return np.nan
    return float(np.sum(vals / (vals + eta)))

def sure_adjusted(X: np.ndarray, y: np.ndarray, tau0: float, lam_adj: float, sigma2: float) -> float:
    beta = fit_baseline_adjusted(X, y, tau0, lam_adj)
    y_hat = predict(X, beta)
    df = empirical_df_adjusted(X, tau0, lam_adj)
    return mse(y, y_hat) + (2.0 * sigma2 * df / X.shape[0]) - sigma2

def sign_label(x: float, tol: float = 1e-10) -> str:
    if x < -tol:
        return "negative"
    if x > tol:
        return "positive"
    return "zero"

def weak_stats(beta_true: np.ndarray, lam: float):
    AW = float(np.sum(beta_true[WEAK_MASK] ** 2))
    AS = float(np.sum(beta_true[~WEAK_MASK] ** 2))
    MW = float(np.sum(EIGS[WEAK_MASK] * beta_true[WEAK_MASK] ** 2))
    MS = float(np.sum(EIGS[~WEAK_MASK] * beta_true[~WEAK_MASK] ** 2))
    BW = float(np.sum(EIGS[WEAK_MASK] * (lam ** 2) / ((EIGS[WEAK_MASK] + lam) ** 2) * beta_true[WEAK_MASK] ** 2))
    BS = float(np.sum(EIGS[~WEAK_MASK] * (lam ** 2) / ((EIGS[~WEAK_MASK] + lam) ** 2) * beta_true[~WEAK_MASK] ** 2))
    rhoW = AW / (AW + AS)
    weak_bias_share = BW / (BW + BS)
    return AW, AS, MW, MS, rhoW, BW, BS, weak_bias_share

def oracle_risk_adjustment(beta_true: np.ndarray, tau0: float, lam_adj: float, noise_std: float, n_train: int = N_TRAIN) -> float:
    eta = tau0 + lam_adj
    sigma_n2 = (noise_std ** 2) / n_train
    bias_term = np.sum(EIGS * (eta ** 2) * (beta_true ** 2) / ((EIGS + eta) ** 2))
    var_term  = sigma_n2 * np.sum((EIGS ** 2) / ((EIGS + eta) ** 2))
    return float(bias_term + var_term)

def oracle_derivative_at_zero(beta_true: np.ndarray, tau0: float, noise_std: float, n_train: int = N_TRAIN) -> float:
    sigma_n2 = (noise_std ** 2) / n_train
    vals = 2.0 * (EIGS ** 2) / ((EIGS + tau0) ** 3) * (tau0 * (beta_true ** 2) - sigma_n2)
    return float(np.sum(vals))

def oracle_best_adjustment(beta_true: np.ndarray, tau0: float, noise_std: float, lam_grid: np.ndarray) -> float:
    risks = np.array([oracle_risk_adjustment(beta_true, tau0, lam, noise_std) for lam in lam_grid], dtype=float)
    return float(lam_grid[np.argmin(risks)])

def select_adjustment_by_sure(X_train, y_train, tau0: float, lam_grid: np.ndarray, sigma2_true: float) -> float:
    best_lam, best_crit = None, None
    for lam in lam_grid:
        if tau0 + lam <= 1e-10:
            continue
        crit = sure_adjusted(X_train, y_train, tau0, lam, sigma2_true)
        if (best_crit is None) or (crit < best_crit):
            best_lam, best_crit = float(lam), float(crit)
    return best_lam

def oracle_best_adjustment_empirical(X_train, y_train, X_test, y_test, tau0: float, lam_grid: np.ndarray):
    best_lam, best_mse = None, None
    for lam in lam_grid:
        if tau0 + lam <= 1e-10:
            continue
        beta = fit_baseline_adjusted(X_train, y_train, tau0, lam)
        te_mse = mse(y_test, predict(X_test, beta))
        if (best_mse is None) or (te_mse < best_mse):
            best_lam, best_mse = float(lam), float(te_mse)
    return best_lam, best_mse

# -------------------------
# Experiment 1
# Feasible Negative Interval + Effective Complexity Increase
# -------------------------
beta_exp1 = make_beta("weak")
noise_exp1 = 0.35
X1_tr, y1_tr, X1_te, y1_te = sample_dataset(beta_exp1, noise_exp1, seed=SEED)
mu_hat_1 = empirical_min_eig(X1_tr)

rep_lams = np.array([
    -0.85 * mu_hat_1,
    -0.60 * mu_hat_1,
    -0.25 * mu_hat_1,
    0.0,
    0.01,
    0.05,
    0.20,
], dtype=float)

rows1 = []
for lam in rep_lams:
    admissible = lam > -mu_hat_1 + 1e-10
    if admissible:
        beta = fit_direct_lambda(X1_tr, y1_tr, lam)
        rows1.append({
            "lambda": lam,
            "region": "negative" if lam < 0 else ("zero" if lam == 0 else "positive"),
            "admissible": True,
            "boundary_margin": lam + mu_hat_1,
            "edf_hat": empirical_df_direct(X1_tr, lam),
            "beta_norm": float(np.linalg.norm(beta)),
            "train_mse": mse(y1_tr, predict(X1_tr, beta)),
            "test_mse": mse(y1_te, predict(X1_te, beta)),
        })
    else:
        rows1.append({
            "lambda": lam,
            "region": "negative",
            "admissible": False,
            "boundary_margin": np.nan,
            "edf_hat": np.nan,
            "beta_norm": np.nan,
            "train_mse": np.nan,
            "test_mse": np.nan,
        })
table1 = pd.DataFrame(rows1)

# -------------------------
# Experiment 2
# Weak-Spectrum Underfitting Structure
# -------------------------
lam_struct = -0.02   # population-feasible because mu_m = 0.04
rows2 = []
for mode in ["weak", "balanced", "strong"]:
    beta_true = make_beta(mode)
    AW, AS, MW, MS, rhoW, BW, BS, weak_bias_share = weak_stats(beta_true, lam_struct)
    rows2.append({
        "alignment": mode,
        "rho_W(kappa)": rhoW,
        "A_W(kappa)": AW,
        "A_S(kappa)": AS,
        "M_W(kappa)": MW,
        "M_S(kappa)": MS,
        "B_W(lambda;kappa)": BW,
        "B_S(lambda;kappa)": BS,
        "weak_bias_share": weak_bias_share,
    })
table2 = pd.DataFrame(rows2)

# -------------------------
# Experiment 3
# Sign-Switch under Baseline Conservativeness
# -------------------------
scenarios3 = [
    ("weak",     0.15, 0.20),
    ("weak",     0.50, 0.20),
    ("balanced", 0.30, 0.10),
    ("balanced", 0.50, 0.20),
    ("strong",   0.30, 0.10),
    ("strong",   0.50, 0.10),
]
rows3 = []
for mode, noise_std, tau0 in scenarios3:
    beta_true = make_beta(mode)
    lam_grid = np.linspace(-tau0 + 1e-3, 1.0, 401)
    deriv0 = oracle_derivative_at_zero(beta_true, tau0, noise_std, N_TRAIN)
    lam_oracle = oracle_best_adjustment(beta_true, tau0, noise_std, lam_grid)
    rows3.append({
        "alignment": mode,
        "noise_std": noise_std,
        "tau0": tau0,
        "dR/dlambda at 0": deriv0,
        "local_negative_predicted": bool(deriv0 > 0),
        "oracle_adjustment": lam_oracle,
        "oracle_adjustment_sign": sign_label(lam_oracle),
    })
table3 = pd.DataFrame(rows3)

# -------------------------
# Experiment 4
# Automatic Selection over the Negative-Capable Family
# -------------------------
scenarios4 = [
    ("weak",     0.15, 0.20),
    ("weak",     0.50, 0.20),
    ("balanced", 0.30, 0.10),
    ("strong",   0.50, 0.10),
]
REPS4 = 80
rows4 = []
for mode, noise_std, tau0 in scenarios4:
    beta_true = make_beta(mode)
    full_grid = np.linspace(-tau0 + 1e-3, 1.0, 61)
    pos_grid = np.linspace(0.0, 1.0, 31)

    oracle_neg = []
    full_sel_neg = []
    pos_mses = []
    full_mses = []
    oracle_mses = []

    for rep in range(REPS4):
        seed = 5000 + 137 * rep + int(100 * noise_std) + int(100 * tau0)
        X_tr, y_tr, X_te, y_te = sample_dataset(beta_true, noise_std, seed=seed)

        oracle_lam, oracle_mse = oracle_best_adjustment_empirical(X_tr, y_tr, X_te, y_te, tau0, full_grid)
        pos_lam = select_adjustment_by_sure(X_tr, y_tr, tau0, pos_grid, noise_std ** 2)
        full_lam = select_adjustment_by_sure(X_tr, y_tr, tau0, full_grid, noise_std ** 2)

        beta_pos = fit_baseline_adjusted(X_tr, y_tr, tau0, pos_lam)
        beta_full = fit_baseline_adjusted(X_tr, y_tr, tau0, full_lam)

        oracle_neg.append(oracle_lam < 0)
        full_sel_neg.append(full_lam < 0)
        pos_mses.append(mse(y_te, predict(X_te, beta_pos)))
        full_mses.append(mse(y_te, predict(X_te, beta_full)))
        oracle_mses.append(oracle_mse)

    rows4.append({
        "alignment": mode,
        "noise_std": noise_std,
        "tau0": tau0,
        "oracle_negative_rate": float(np.mean(oracle_neg)),
        "selector_negative_rate": float(np.mean(full_sel_neg)),
        "positive_only_test_mse": float(np.mean(pos_mses)),
        "negative_capable_test_mse": float(np.mean(full_mses)),
        "oracle_test_mse": float(np.mean(oracle_mses)),
        "negcap_minus_positive": float(np.mean(full_mses) - np.mean(pos_mses)),
        "negcap_oracle_gap": float(np.mean(full_mses) - np.mean(oracle_mses)),
    })
table4 = pd.DataFrame(rows4)

# -------------------------
# Print exactly 4 tables
# -------------------------
pd.set_option("display.max_columns", 50)
pd.set_option("display.width", 200)
pd.set_option("display.float_format", lambda x: f"{x:0.6f}")

print("\n[Experiment 1] Feasible Negative Interval and Effective Complexity Increase")
display(table1.round(6))

print("\n[Experiment 2] Weak-Spectrum Underfitting Structure")
display(table2.round(6))

print("\n[Experiment 3] Sign-Switch under Baseline Conservativeness")
display(table3.round(6))

print("\n[Experiment 4] Automatic Selection over the Negative-Capable Family")
display(table4.round(6))

"""# Exp 5"""

# ============================================================
# Experiment 5: Semi-Synthetic Real-Covariance Regression
# - Real X from multiple regression datasets
# - Fixed representation from unsupervised preprocessing + PCA
# - Synthetic y generated on the real covariance geometry
# - Weak / Balanced / Strong oracle alignments
# - Automatic selection over a baseline-adjusted negative-capable family
# - Selector: SURE with known noise variance
# Output: only 2 compact summary tables
# ============================================================

import sys
import subprocess
import warnings
warnings.filterwarnings("ignore")

# ---- install ucimlrepo if needed ----
try:
    from ucimlrepo import fetch_ucirepo
except Exception:
    subprocess.check_call([sys.executable, "-m", "pip", "-q", "install", "ucimlrepo"])
    from ucimlrepo import fetch_ucirepo

import hashlib
import numpy as np
import pandas as pd
from IPython.display import display

from sklearn.datasets import fetch_california_housing, load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

# -------------------------
# Global configuration
# -------------------------
SEED = 23
REPEATS = 20
TEST_SIZE = 0.30

TRAIN_FRACS = [0.02, 0.05, 0.10]
ALIGNMENTS = ["weak", "balanced", "strong"]
NOISE_LEVELS = {
    "low": 0.20,
    "high": 0.50,
}

# Fixed representation for semi-synthetic environment
SOURCE_PCA_CAP = 24
FINAL_REPR_DIM = 12
MIN_FINAL_DIM = 8
TOP_SHARE = 0.60

# Conservative positive baseline tau0 = TAU0_MULT * median(eigs)
TAU0_MULT = 0.75

# Candidate adjustment grids around the baseline tau0
POS_GRID_SIZE = 28
NEG_GRID_SIZE = 28

MIN_DATASETS_REQUIRED = 5
MIN_TRAIN = FINAL_REPR_DIM + 6
SIGNAL_STD = 1.0

# -------------------------
# Utility functions
# -------------------------
def stable_int_seed(*parts, mod=2_000_000_000):
    s = "||".join(map(str, parts)).encode("utf-8")
    h = hashlib.sha256(s).hexdigest()
    return int(h[:12], 16) % mod

def _coerce_target(y):
    if isinstance(y, pd.DataFrame):
        if y.shape[1] == 1:
            y = y.iloc[:, 0]
        else:
            y = y.iloc[:, 0]
    elif not isinstance(y, pd.Series):
        y = pd.Series(y)
    y = pd.to_numeric(y, errors="coerce")
    return y

def _finalize_xy(X, y, name):
    X = X.copy()
    y = _coerce_target(y)

    mask = y.notna()
    X = X.loc[mask].reset_index(drop=True)
    y = y.loc[mask].reset_index(drop=True).astype(float)

    keep = ~X.isna().all(axis=1)
    X = X.loc[keep].reset_index(drop=True)
    y = y.loc[keep].reset_index(drop=True)

    return {"name": name, "X": X, "y": y}

def _metadata_target_col(ds):
    meta = getattr(ds, "metadata", None)
    if meta is None:
        return None
    if isinstance(meta, dict):
        return meta.get("target_col", None)
    return getattr(meta, "target_col", None)

def _variables_target_candidates(ds):
    vars_df = getattr(ds, "variables", None)
    if vars_df is None or not isinstance(vars_df, pd.DataFrame):
        return []

    cols_lower = {str(c).strip().lower(): c for c in vars_df.columns}
    name_col = cols_lower.get("name", None)
    role_col = cols_lower.get("role", None)
    if name_col is None or role_col is None:
        return []

    out = []
    for _, row in vars_df.iterrows():
        role = str(row[role_col]).strip().lower()
        if role == "target":
            out.append(row[name_col])
    return out

def _resolve_target_from_ucirepo(ds, dataset_name, preferred_target=None):
    X = ds.data.features.copy()
    y = ds.data.targets.copy()

    if not isinstance(y, pd.DataFrame):
        return X, y

    cols = list(y.columns)
    norm_map = {str(c).strip().lower(): c for c in cols}

    if preferred_target is not None:
        key = str(preferred_target).strip().lower()
        if preferred_target in cols:
            return X, y[preferred_target]
        if key in norm_map:
            return X, y[norm_map[key]]

    meta_target = _metadata_target_col(ds)
    if meta_target is not None:
        if isinstance(meta_target, (list, tuple)) and len(meta_target) > 0:
            meta_target = meta_target[0]
        key = str(meta_target).strip().lower()
        if meta_target in cols:
            return X, y[meta_target]
        if key in norm_map:
            return X, y[norm_map[key]]

    candidates = _variables_target_candidates(ds)
    for cand in candidates:
        key = str(cand).strip().lower()
        if cand in cols:
            return X, y[cand]
        if key in norm_map:
            return X, y[norm_map[key]]

    if y.shape[1] == 1:
        return X, y.iloc[:, 0]

    heuristic_names = [
        "target", "y", "output", "response", "label", "quality",
        "rings", "price", "heating load", "scaled sound pressure",
        "scaled-sound-pressure", "concrete compressive strength"
    ]
    for h in heuristic_names:
        if h in norm_map:
            return X, y[norm_map[h]]

    print(f"[warn] target not uniquely resolved for {dataset_name}; using first target column: {cols[0]}")
    return X, y.iloc[:, 0]

# -------------------------
# Dataset loaders
# -------------------------
def load_california():
    data = fetch_california_housing(as_frame=True)
    return _finalize_xy(data.data, data.target, "california_housing")

def load_diabetes_builtin():
    data = load_diabetes(as_frame=True)
    return _finalize_xy(data.data, data.target, "diabetes")

def load_uci_safe(uci_id, name, preferred_target=None):
    ds = fetch_ucirepo(id=uci_id)
    X, y = _resolve_target_from_ucirepo(ds, name, preferred_target=preferred_target)
    return _finalize_xy(X, y, name)

DATASET_LOADERS = [
    load_california,
    load_diabetes_builtin,
    lambda: load_uci_safe(1,   "abalone", preferred_target="Rings"),
    lambda: load_uci_safe(165, "concrete_compressive_strength", preferred_target="Concrete compressive strength"),
    lambda: load_uci_safe(186, "wine_quality", preferred_target="quality"),
    lambda: load_uci_safe(242, "energy_efficiency_heating", preferred_target="Y1"),
    lambda: load_uci_safe(291, "airfoil_self_noise", preferred_target="scaled-sound-pressure"),
]

# -------------------------
# Fixed full-dataset preprocessing
# -------------------------
def prepare_full_design(X_df):
    X = X_df.copy()

    for c in X.columns:
        if str(X[c].dtype) == "bool":
            X[c] = X[c].astype(int)

    num_cols = X.select_dtypes(include=[np.number]).columns.tolist()
    cat_cols = [c for c in X.columns if c not in num_cols]

    X_num = X[num_cols].copy() if num_cols else pd.DataFrame(index=X.index)
    for c in X_num.columns:
        med = X_num[c].median()
        if pd.isna(med):
            med = 0.0
        X_num[c] = X_num[c].fillna(med)

    X_cat = X[cat_cols].copy() if cat_cols else pd.DataFrame(index=X.index)
    if len(cat_cols) > 0:
        for c in X_cat.columns:
            mode = X_cat[c].mode(dropna=True)
            fill = str(mode.iloc[0]) if len(mode) > 0 else "missing"
            X_cat[c] = X_cat[c].fillna(fill).astype(str)
        X_cat = pd.get_dummies(X_cat, drop_first=False)

    X_full = pd.concat(
        [X_num.reset_index(drop=True), X_cat.reset_index(drop=True)],
        axis=1
    )

    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X_full)
    return X_scaled, X_full.shape[1]

def _select_mixed_indices(total_dim, target_dim, top_share=0.60):
    n_top = int(np.ceil(top_share * target_dim))
    n_top = min(max(1, n_top), target_dim)
    n_bottom = target_dim - n_top

    idx = list(range(n_top))
    if n_bottom > 0:
        idx += list(range(total_dim - n_bottom, total_dim))

    idx = list(dict.fromkeys(idx))
    if len(idx) < target_dim:
        for j in range(total_dim):
            if j not in idx:
                idx.append(j)
            if len(idx) == target_dim:
                break

    return np.array(sorted(idx), dtype=int)

def build_fixed_representation(X_scaled):
    n, p = X_scaled.shape
    pca_cap = min(SOURCE_PCA_CAP, p, max(2, n - 2))
    pca = PCA(n_components=pca_cap, svd_solver="full", random_state=SEED)
    Z_cap = pca.fit_transform(X_scaled)
    eigs_cap = pca.explained_variance_.astype(float)

    target_dim = min(FINAL_REPR_DIM, pca_cap)
    if pca_cap >= MIN_FINAL_DIM:
        target_dim = max(MIN_FINAL_DIM, target_dim)

    idx = _select_mixed_indices(pca_cap, target_dim, top_share=TOP_SHARE)
    Z = Z_cap[:, idx]
    eigs = eigs_cap[idx]

    return Z, eigs, len(idx), pca_cap

# -------------------------
# Semi-synthetic signal construction
# -------------------------
def make_beta_pattern(eigs, alignment, signal_std=1.0):
    m = len(eigs)
    base = np.geomspace(1.0, 0.15, m)

    if alignment == "strong":
        raw = base.copy()
    elif alignment == "weak":
        raw = base[::-1].copy()
    elif alignment == "balanced":
        raw = np.ones(m, dtype=float)
    else:
        raise ValueError("alignment must be one of {'weak','balanced','strong'}")

    raw = raw / np.linalg.norm(raw)
    signal_var = float(np.sum(eigs * (raw ** 2)))
    beta = signal_std * raw / np.sqrt(max(signal_var, 1e-12))
    return beta

def weak_mass_ratio(beta):
    m = len(beta)
    k_weak = max(2, int(np.ceil(0.40 * m)))
    weak_idx = np.arange(m - k_weak, m)
    aw = float(np.sum(beta[weak_idx] ** 2))
    at = float(np.sum(beta ** 2))
    return aw / max(at, 1e-12)

# -------------------------
# Baseline-adjusted negative-capable ridge
# -------------------------
def sigma_hat(X):
    return (X.T @ X) / X.shape[0]

def g_hat(X, y):
    return (X.T @ y) / X.shape[0]

def min_eig_empirical(X):
    vals = np.linalg.eigvalsh(sigma_hat(X))
    return float(vals.min())

def fit_adjusted_ridge(X, y, tau0, adj):
    eta = tau0 + adj
    A = sigma_hat(X) + eta * np.eye(X.shape[1])
    b = g_hat(X, y)
    try:
        beta = np.linalg.solve(A, b)
    except np.linalg.LinAlgError:
        beta = np.linalg.pinv(A) @ b
    return beta

def predict(X, beta):
    return X @ beta

def mse(y_true, y_pred):
    return float(np.mean((y_true - y_pred) ** 2))

def rmse(y_true, y_pred):
    return float(np.sqrt(mse(y_true, y_pred)))

def empirical_df_adjusted(X, tau0, adj):
    eta = tau0 + adj
    vals = np.linalg.eigvalsh(sigma_hat(X))
    if eta <= 1e-12 or np.any(vals + eta <= 1e-12):
        return np.nan
    return float(np.sum(vals / (vals + eta)))

def sure_adjusted(X, y, tau0, adj, sigma2):
    eta = tau0 + adj
    if eta <= 1e-12:
        return np.inf
    beta = fit_adjusted_ridge(X, y, tau0, adj)
    y_hat = predict(X, beta)
    df = empirical_df_adjusted(X, tau0, adj)
    if not np.isfinite(df):
        return np.inf
    return mse(y, y_hat) + (2.0 * sigma2 * df / X.shape[0]) - sigma2

def select_adj_by_sure(X, y, tau0, grid, sigma2):
    best_adj, best_score = None, None
    for adj in grid:
        score = sure_adjusted(X, y, tau0, adj, sigma2)
        if np.isfinite(score) and ((best_score is None) or (score < best_score)):
            best_adj, best_score = float(adj), float(score)
    return best_adj

def oracle_best_adj(X_train, y_train, X_test, y_test, tau0, grid):
    best_adj, best_rmse = None, None
    for adj in grid:
        beta = fit_adjusted_ridge(X_train, y_train, tau0, adj)
        te_rmse = rmse(y_test, predict(X_test, beta))
        if (best_rmse is None) or (te_rmse < best_rmse):
            best_adj, best_rmse = float(adj), float(te_rmse)
    return best_adj, best_rmse

def make_adjustment_grids(tau0):
    pos = tau0 * np.r_[0.0, np.logspace(-3, 1.0, POS_GRID_SIZE)]
    neg = -tau0 * np.r_[0.95, 0.90, 0.85, np.linspace(0.75, 0.05, NEG_GRID_SIZE)]
    pos = np.unique(np.asarray(pos, dtype=float))
    neg = np.unique(np.asarray(neg, dtype=float))
    full = np.unique(np.r_[neg, pos])
    return pos, full

def oracle_derivative_zero(eigs, beta, tau0, noise_std, n_train):
    sigma_n2 = (noise_std ** 2) / n_train
    vals = 2.0 * (eigs ** 2) / ((eigs + tau0) ** 3) * (tau0 * (beta ** 2) - sigma_n2)
    return float(np.sum(vals))

# -------------------------
# Load datasets and build fixed representations
# -------------------------
datasets = []
for loader in DATASET_LOADERS:
    try:
        ds = loader()
        X_scaled, encoded_p = prepare_full_design(ds["X"])
        Z_full, eigs_full, repr_dim, source_dim = build_fixed_representation(X_scaled)

        datasets.append({
            "name": ds["name"],
            "Z_full": Z_full,
            "eigs_full": eigs_full,
            "repr_dim": repr_dim,
            "encoded_p": encoded_p,
            "n_total": Z_full.shape[0],
        })
    except Exception as e:
        print(f"[skip] loader failed: {loader} -> {type(e).__name__}: {e}")

if len(datasets) < MIN_DATASETS_REQUIRED:
    raise RuntimeError(
        f"Only {len(datasets)} datasets were loaded successfully; need at least {MIN_DATASETS_REQUIRED}."
    )

print("Loaded datasets:", ", ".join([d["name"] for d in datasets]))

# -------------------------
# Run experiment 5A
# -------------------------
all_rows = []

for ds in datasets:
    name = ds["name"]
    Z_full = ds["Z_full"]
    eigs_full = ds["eigs_full"]
    repr_dim = ds["repr_dim"]
    encoded_p = ds["encoded_p"]
    n_total = ds["n_total"]

    tau0 = TAU0_MULT * float(np.median(eigs_full))
    tau0 = max(tau0, 1e-4)

    for alignment in ALIGNMENTS:
        beta_star = make_beta_pattern(eigs_full, alignment, signal_std=SIGNAL_STD)
        rho_w = weak_mass_ratio(beta_star)
        noiseless_signal = Z_full @ beta_star

        for noise_name, noise_std in NOISE_LEVELS.items():
            sigma2_true = noise_std ** 2

            for train_frac in TRAIN_FRACS:
                for rep in range(REPEATS):
                    seed = stable_int_seed(SEED, name, alignment, noise_name, train_frac, rep)
                    rng = np.random.default_rng(seed)

                    y_full = noiseless_signal + rng.normal(scale=noise_std, size=n_total)

                    idx_all = np.arange(n_total)
                    idx_pool, idx_test = train_test_split(
                        idx_all, test_size=TEST_SIZE, random_state=seed
                    )

                    n_pool = len(idx_pool)
                    n_train = int(round(train_frac * n_pool))
                    n_train = max(MIN_TRAIN, n_train)
                    n_train = min(n_train, n_pool - 2)

                    idx_train = rng.choice(idx_pool, size=n_train, replace=False)

                    Ztr = Z_full[idx_train]
                    ytr = y_full[idx_train]
                    Zte = Z_full[idx_test]
                    yte = y_full[idx_test]

                    mu_min_hat = min_eig_empirical(Ztr)

                    pos_grid, full_grid = make_adjustment_grids(tau0)

                    oracle_adj, oracle_rmse = oracle_best_adj(Ztr, ytr, Zte, yte, tau0, full_grid)
                    pos_adj = select_adj_by_sure(Ztr, ytr, tau0, pos_grid, sigma2_true)
                    full_adj = select_adj_by_sure(Ztr, ytr, tau0, full_grid, sigma2_true)

                    beta_pos = fit_adjusted_ridge(Ztr, ytr, tau0, pos_adj)
                    beta_full = fit_adjusted_ridge(Ztr, ytr, tau0, full_adj)

                    pos_rmse = rmse(yte, predict(Zte, beta_pos))
                    negcap_rmse = rmse(yte, predict(Zte, beta_full))

                    deriv0 = oracle_derivative_zero(
                        eigs=eigs_full,
                        beta=beta_star,
                        tau0=tau0,
                        noise_std=noise_std,
                        n_train=n_train,
                    )

                    all_rows.append({
                        "dataset": name,
                        "alignment": alignment,
                        "noise": noise_name,
                        "noise_std": noise_std,
                        "train_frac": train_frac,
                        "repeat": rep,
                        "n_train": n_train,
                        "encoded_p": encoded_p,
                        "repr_dim": repr_dim,
                        "tau0": tau0,
                        "rho_w": rho_w,
                        "mu_min_hat": mu_min_hat,
                        "local_negative_predicted": float(deriv0 > 0.0),
                        "oracle_negative": float(oracle_adj < 0.0),
                        "selector_negative": float(full_adj < 0.0),
                        "oracle_adj": oracle_adj,
                        "selector_adj": full_adj,
                        "pos_adj": pos_adj,
                        "pos_rmse": pos_rmse,
                        "negcap_rmse": negcap_rmse,
                        "oracle_rmse": oracle_rmse,
                        "negcap_minus_pos": negcap_rmse - pos_rmse,
                        "negcap_oracle_gap": negcap_rmse - oracle_rmse,
                        "win_vs_pos": float(negcap_rmse < pos_rmse),
                    })

raw_results = pd.DataFrame(all_rows)

# -------------------------
# Compact summary tables for paper
# -------------------------
def _safe_rel_gain(pos, neg):
    return 100.0 * (pos - neg) / max(pos, 1e-12)

# Table 1: main result summary by alignment × noise
paper_table_main = (
    raw_results
    .groupby(["alignment", "noise"], as_index=False)
    .agg(
        rhoW=("rho_w", "mean"),
        oracle_neg=("oracle_negative", "mean"),
        select_neg=("selector_negative", "mean"),
        pos_rmse=("pos_rmse", "mean"),
        neg_rmse=("negcap_rmse", "mean"),
        oracle_rmse=("oracle_rmse", "mean"),
        win_rate=("win_vs_pos", "mean"),
        gap_to_oracle=("negcap_oracle_gap", "mean"),
    )
)

paper_table_main["gain_pct"] = [
    _safe_rel_gain(p, n)
    for p, n in zip(paper_table_main["pos_rmse"], paper_table_main["neg_rmse"])
]

paper_table_main = (
    paper_table_main[
        ["alignment", "noise", "rhoW", "oracle_neg", "select_neg",
         "pos_rmse", "neg_rmse", "gain_pct", "gap_to_oracle", "win_rate"]
    ]
    .sort_values(["alignment", "noise"])
    .reset_index(drop=True)
)

# Table 2: sensitivity to train fraction, aggregated within alignment
paper_table_size = (
    raw_results
    .groupby(["alignment", "train_frac"], as_index=False)
    .agg(
        oracle_neg=("oracle_negative", "mean"),
        select_neg=("selector_negative", "mean"),
        pos_rmse=("pos_rmse", "mean"),
        neg_rmse=("negcap_rmse", "mean"),
        oracle_rmse=("oracle_rmse", "mean"),
        win_rate=("win_vs_pos", "mean"),
        gap_to_oracle=("negcap_oracle_gap", "mean"),
    )
)

paper_table_size["gain_pct"] = [
    _safe_rel_gain(p, n)
    for p, n in zip(paper_table_size["pos_rmse"], paper_table_size["neg_rmse"])
]

paper_table_size = (
    paper_table_size[
        ["alignment", "train_frac", "oracle_neg", "select_neg",
         "pos_rmse", "neg_rmse", "gain_pct", "gap_to_oracle", "win_rate"]
    ]
    .sort_values(["alignment", "train_frac"])
    .reset_index(drop=True)
)

# Pretty labels
paper_table_main["alignment"] = paper_table_main["alignment"].map({
    "weak": "Weak",
    "balanced": "Balanced",
    "strong": "Strong",
})
paper_table_main["noise"] = paper_table_main["noise"].map({
    "low": "Low",
    "high": "High",
})

paper_table_size["alignment"] = paper_table_size["alignment"].map({
    "weak": "Weak",
    "balanced": "Balanced",
    "strong": "Strong",
})

# -------------------------
# Output only 2 compact tables
# -------------------------
pd.set_option("display.max_columns", 50)
pd.set_option("display.width", 180)
pd.set_option("display.float_format", lambda x: f"{x:0.4f}")

print("\n[Table 1] Main Summary by alignment × noise")
display(paper_table_main)

print("\n[Table 2] Summary by alignment × train_frac")
display(paper_table_size)